from logging.config import fileConfig

from sqlalchemy import engine_from_config, pool

from alembic import context

# Registers every mapper with app.db.Base.metadata (app/models/__init__.py's docstring) and
# gives autogenerate something to diff against. Importing app.config here too, rather than
# duplicating GRADINGHELPER_DATABASE_URL's default/env-var name in alembic.ini, is what keeps
# `alembic upgrade head` pointed at the same database the app itself would open — see
# run_migrations_online() below, which overrides alembic.ini's sqlalchemy.url with it.
from app import models  # noqa: F401
from app.config import get_settings
from app.db import Base

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config

# Interpret the config file for Python logging.
# This line sets up loggers basically.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata

# other values from the config, defined by the needs of env.py,
# can be acquired:
# my_important_option = config.get_main_option("my_important_option")
# ... etc.


# app.config.get_settings() (GRADINGHELPER_DATABASE_URL, same default as the running app) wins
# over alembic.ini's sqlalchemy.url placeholder — one source of truth for "which database",
# rather than an operator having to keep two settings in sync.
config.set_main_option("sqlalchemy.url", get_settings().database_url)


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    This configures the context with just a URL
    and not an Engine, though an Engine is acceptable
    here as well.  By skipping the Engine creation
    we don't even need a DBAPI to be available.

    Calls to context.execute() here emit the given string to the
    script output.

    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        render_as_batch=True,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine
    and associate a connection with the context.

    """
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        # render_as_batch=True: SQLite can't ALTER a column/constraint in place, so any future
        # autogenerated migration beyond this initial one needs Alembic's batch mode (rebuild
        # table, copy rows, swap in) to run at all. Harmless for pure CREATE TABLE migrations
        # like this one.
        context.configure(
            connection=connection, target_metadata=target_metadata, render_as_batch=True
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
