from logging.config import fileConfig

from sqlalchemy import engine_from_config, pool

from alembic import context

# Registers every mapper with app.db.Base.metadata (app/models/__init__.py's docstring) and
# gives autogenerate something to diff against. Importing app.config here too, rather than
# duplicating GRADINGHELPER_DATABASE_URL's default/env-var name in alembic.ini, is what keeps
# `alembic upgrade head` pointed at the same database the app itself would open — see
# run_migrations_online() below, which overrides alembic.ini's sqlalchemy.url with it.
from app import models  # noqa: F401
from app.config import get_settings
from app.db import Base

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config

# Interpret the config file for Python logging.
# This line sets up loggers basically.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata

# other values from the config, defined by the needs of env.py,
# can be acquired:
# my_important_option = config.get_main_option("my_important_option")
# ... etc.


# app.config.get_settings() (GRADINGHELPER_DATABASE_URL, same default as the running app) wins
# over alembic.ini's sqlalchemy.url placeholder — one source of truth for "which database",
# rather than an operator having to keep two settings in sync.
config.set_main_option("sqlalchemy.url", get_settings().database_url)


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    This configures the context with just a URL
    and not an Engine, though an Engine is acceptable
    here as well.  By skipping the Engine creation
    we don't even need a DBAPI to be available.

    Calls to context.execute() here emit the given string to the
    script output.

    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        render_as_batch=True,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine
    and associate a connection with the context.

    """
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        # Importing app.db (above) registers its `PRAGMA foreign_keys=ON` listener on every
        # SQLAlchemy Engine in this process (app/db.py::_set_sqlite_pragmas is attached to the
        # Engine *class*, not one instance), including this migration-only engine. That collides
        # with Alembic's own "turn foreign_keys off while a batch op recreates a table" safety
        # net: SQLite refuses to change that pragma once a transaction is open, and one already
        # is by the time a batch op tries — Alembic's toggle silently becomes a no-op. Recreating
        # any table with incoming `ondelete="CASCADE"` foreign keys (e.g. "exams", which
        # "student_registrations"/"exercises"/"grade_thresholds" all reference) then runs its
        # internal `DROP TABLE` step with enforcement genuinely on, which cascade-deletes every
        # child row for real — silent, irreversible data loss discovered while writing the
        # 8ab4f293a4ce migration. Turning it off here, before `context.begin_transaction()` opens
        # anything, is what makes the pragma change actually stick for the whole migration run.
        if connection.dialect.name == "sqlite":
            connection.exec_driver_sql("PRAGMA foreign_keys=OFF")
            # SQLAlchemy autobegins a Core-level transaction on that first statement; leaving it
            # open here would make `context.begin_transaction()` below nest inside it instead of
            # starting its own, and alembic's final `alembic_version` stamp would then never
            # reach a real commit. Close it out before alembic takes over the connection.
            connection.commit()

        # render_as_batch=True: SQLite can't ALTER a column/constraint in place, so any future
        # autogenerated migration beyond this initial one needs Alembic's batch mode (rebuild
        # table, copy rows, swap in) to run at all. Harmless for pure CREATE TABLE migrations
        # like this one.
        context.configure(
            connection=connection, target_metadata=target_metadata, render_as_batch=True
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
