"""initial schema

Revision ID: fb8602eb97b1
Revises:
Create Date: 2026-08-03 17:28:37.296897

Hand-adjusted after autogeneration: added the ``app.types`` import that autogenerate references
(``DecimalText``, see app/types.py) but never imports itself — every points/percentage column
below (§7.0) depends on it rather than a bare ``sa.Numeric``/``sa.Float``.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

import app.types
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fb8602eb97b1"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=150), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_username"), ["username"], unique=True)

    op.create_table(
        "lectures",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lectures", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_lectures_owner_id"), ["owner_id"], unique=False)

    op.create_table(
        "user_sessions",
        sa.Column("token", sa.String(length=128), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("token"),
    )
    with op.batch_alter_table("user_sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "exams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lecture_id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("semester", sa.String(length=64), nullable=False),
        sa.Column("termin", sa.String(length=64), nullable=False),
        sa.Column("exam_date", sa.Date(), nullable=True),
        sa.Column(
            "bonus_mode",
            sa.Enum(
                "ALWAYS",
                "ONLY_IF_PASSING_WITHOUT_BONUS",
                name="bonusmode",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["lecture_id"], ["lectures.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("exams", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_exams_lecture_id"), ["lecture_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_exams_owner_id"), ["owner_id"], unique=False)

    op.create_table(
        "exercises",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("exam_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("max_points", app.types.DecimalText(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["exam_id"], ["exams.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("exam_id", "position", name="uq_exercise_exam_position"),
    )
    with op.batch_alter_table("exercises", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_exercises_exam_id"), ["exam_id"], unique=False)

    op.create_table(
        "grade_thresholds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("exam_id", sa.Integer(), nullable=False),
        sa.Column("grade", sa.String(length=8), nullable=False),
        sa.Column("percentage", app.types.DecimalText(), nullable=False),
        sa.ForeignKeyConstraint(["exam_id"], ["exams.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("exam_id", "grade", name="uq_grade_threshold_exam_grade"),
    )
    with op.batch_alter_table("grade_thresholds", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_grade_thresholds_exam_id"), ["exam_id"], unique=False)

    op.create_table(
        "student_registrations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("exam_id", sa.Integer(), nullable=False),
        sa.Column("matrikelnummer", sa.String(length=64), nullable=False),
        sa.Column("nachname", sa.String(length=255), nullable=False),
        sa.Column("vorname", sa.String(length=255), nullable=False),
        sa.Column("course_code", sa.String(length=255), nullable=False),
        sa.Column("module_title", sa.Text(), nullable=False),
        sa.Column("versuch", sa.Integer(), nullable=False),
        sa.Column("kommentar", sa.Text(), nullable=True),
        sa.Column("flagged", sa.Boolean(), nullable=False),
        sa.Column("excluded", sa.Boolean(), nullable=False),
        sa.Column("attended", sa.Boolean(), nullable=True),
        sa.Column("bonus_points", app.types.DecimalText(), nullable=False),
        sa.Column("source_filename", sa.String(length=512), nullable=True),
        sa.ForeignKeyConstraint(["exam_id"], ["exams.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "exam_id", "matrikelnummer", name="uq_registration_exam_matrikelnummer"
        ),
    )
    with op.batch_alter_table("student_registrations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_student_registrations_exam_id"), ["exam_id"], unique=False
        )

    op.create_table(
        "exercise_points",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("registration_id", sa.Integer(), nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("points", app.types.DecimalText(), nullable=False),
        sa.ForeignKeyConstraint(["exercise_id"], ["exercises.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["registration_id"], ["student_registrations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "registration_id", "exercise_id", name="uq_points_registration_exercise"
        ),
    )
    with op.batch_alter_table("exercise_points", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_exercise_points_exercise_id"), ["exercise_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_exercise_points_registration_id"), ["registration_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("exercise_points", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exercise_points_registration_id"))
        batch_op.drop_index(batch_op.f("ix_exercise_points_exercise_id"))

    op.drop_table("exercise_points")
    with op.batch_alter_table("student_registrations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_student_registrations_exam_id"))

    op.drop_table("student_registrations")
    with op.batch_alter_table("grade_thresholds", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_grade_thresholds_exam_id"))

    op.drop_table("grade_thresholds")
    with op.batch_alter_table("exercises", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exercises_exam_id"))

    op.drop_table("exercises")
    with op.batch_alter_table("exams", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exams_owner_id"))
        batch_op.drop_index(batch_op.f("ix_exams_lecture_id"))

    op.drop_table("exams")
    with op.batch_alter_table("user_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_sessions_user_id"))

    op.drop_table("user_sessions")
    with op.batch_alter_table("lectures", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lectures_owner_id"))

    op.drop_table("lectures")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))

    op.drop_table("users")
    # ### end Alembic commands ###
